export default ref([
  { nome: 'Pizza', preco: '50,00', img: '/pizza.jpg', descricao: 'Pizza de calabresa', sobre: 'A pizza de calabresa é uma iguaria irresistível, com uma base de massa fina ou grossa, coberta por molho de tomate, queijo mussarela derretido e fatias de calabresa bem temperada. O sabor picante e defumado da calabresa se mistura perfeitamente com a suavidade do queijo, criando uma combinação deliciosa e cheia de personalidade.', to: '/comida/1', id: '1' },
  { nome: 'Hamburguer', preco: '20,00', img: '/hamburguer.jpg', descricao: 'Hamburguer de carne', sobre: 'O hambúrguer de carne é uma deliciosa combinação de carne moída, geralmente bovina, moldada em um disco e grelhada até atingir o ponto desejado. Ele é comumente servido em um pão macio, acompanhado de ingredientes como queijo, alface, tomate, cebola, picles e molhos, criando um sabor suculento e equilibrado.', to: '/comida/2', id: '2' },
  { nome: 'Cachorro quente', preco: '10,00', img: '/cachorroquente.jpeg', descricao: 'Cachorro quente com molho', sobre:'O cachorro-quente é um lanche tradicional composto por uma salsicha cozida ou grelhada, servida em um pão macio. Ele pode ser incrementado com uma variedade de acompanhamentos, como ketchup, mostarda, maionese, relish, cebola, batata palha e até queijo. Simples, prático e saboroso, é uma escolha popular para refeições rápidas e descontraídas.', to: '/comida/3', id: '3' },
  { nome: 'Japa', preco: '45,00', img: '/japa.jpeg', descricao: 'Sushi', sobre:'O sushi é um prato típico da culinária japonesa, composto por arroz temperado com vinagre, acompanhado de peixe cru, frutos do mar ou vegetais, e servido geralmente com algas nori. Pode ser preparado em diferentes formas, como nigiri, sashimi e maki.', to: '/comida/4', id: '4' },
  { nome: 'Taco', preco: '30,00', img: '/taco.jpg', descricao: 'Taco de carne', sobre: 'O taco é um prato típico da culinária mexicana, composto por uma tortilla crocante ou macia, recheada com uma variedade de ingredientes como carne moída, frango, peixe, feijão, queijo, alface, tomate e guacamole. É uma explosão de sabores e texturas, perfeito para quem aprecia uma refeição prática e cheia de tempero, com um toque picante e fresco.', to: '/comida/5', id: '5' },
  { nome: 'Lasanha', preco: '25,00', img: '/lasanha.jpeg', descricao: 'Lasanha de carne', sobre:'A lasanha é um prato clássico da culinária italiana, composto por camadas de massa intercaladas com molho de carne ou frango, queijo, molho béchamel e temperos. Ao ser assada, a combinação de sabores se mistura perfeitamente, criando uma refeição rica, cremosa e irresistível. Ideal para quem busca uma refeição reconfortante e cheia de sabor.', to: '/comida/6', id: '6' },
  { nome: 'Burrito', preco: '12,00', img: '/burrito.jpg', descricao: 'Burrito de frango', sobre:'O burrito de frango é uma delícia da cozinha mexicana, composto por uma tortilla de trigo recheada com peito de frango desfiado, arroz, feijão, queijo, guacamole, alface e salsa. Tudo enrolado de forma compacta, criando uma refeição prática e cheia de sabores intensos, com um toque leve e fresco que agrada a todos os paladares.', to: '/comida/7', id: '7' },
  { nome: 'Batata frita', preco: '13,00', img: '/batatafrita.jpg', descricao: 'Batata frita grande', sobre:'A batata frita é um clássico acompanhamento crocante por fora e macio por dentro. Cortada em tiras finas ou grossas, ela é frita até ficar dourada e irresistível, oferecendo um sabor simples, mas delicioso. Ideal para acompanhar pratos diversos ou ser saboreada sozinha, com molhos de sua preferência.', to: '/comida/8', id: '8' },
])
